export const topicMetaMap = {
  // Economy, Business & Finance
  "topic_economy,_business_and_finance": "Economy, Business & Finance",
  "topic_textile_and_clothing": "Economy, Business & Finance",
  "topic_clothing": "Economy, Business & Finance",
  "topic_economy": "Economy, Business & Finance",
  "topic_consumer_goods": "Economy, Business & Finance",
  "topic_luxury_good": "Economy, Business & Finance",
  "topic_beverage": "Economy, Business & Finance",
  "topic_media_and_entertainment_industry": "Economy, Business & Finance",
  "topic_automotive": "Economy, Business & Finance",
  "topic_debt_market": "Economy, Business & Finance",
  "topic_online_shopping": "Economy, Business & Finance",
  "topic_consumer_electronics": "Economy, Business & Finance",
  "topic_film_industry": "Economy, Business & Finance",
  "topic_health_and_beauty_product": "Economy, Business & Finance",
  "topic_tour_operator": "Economy, Business & Finance",
  "topic_tourism_and_leisure_industry": "Economy, Business & Finance",
  "topic_department_store": "Economy, Business & Finance",
  "topic_hotel_and_accommodation": "Economy, Business & Finance",
  "topic_books_and_publishing": "Economy, Business & Finance",
  "topic_specialty_store": "Economy, Business & Finance",
  "topic_furnishings_and_furniture": "Economy, Business & Finance",
  "topic_agriculture": "Economy, Business & Finance",
  "topic_securities": "Economy, Business & Finance",
  "topic_business_information": "Economy, Business & Finance",
  "topic_toy_and_game": "Economy, Business & Finance",
  "topic_payment_service": "Economy, Business & Finance",
  "topic_business_service": "Economy, Business & Finance",
  "topic_currency": "Economy, Business & Finance",
  "topic_grocery": "Economy, Business & Finance",
  "topic_beverage_and_grocery": "Economy, Business & Finance",
  "topic_music_industry": "Economy, Business & Finance",
  "topic_banking": "Economy, Business & Finance",
  "topic_financial_service": "Economy, Business & Finance",
  "topic_prices": "Economy, Business & Finance",
  "topic_inflation": "Economy, Business & Finance",
  "topic_consumer_issue": "Economy, Business & Finance",
  "topic_loans_and_lending": "Economy, Business & Finance",
  "topic_mortgages": "Economy, Business & Finance",
  "topic_commercial_fishing": "Economy, Business & Finance",
  "topic_personal_income": "Economy, Business & Finance",
  "topic_personal_finance_and_investment": "Economy, Business & Finance",
  "topic_business_reporting_and_performance": "Economy, Business & Finance",
  "topic_credit_rating": "Economy, Business & Finance",
  "topic_business_enterprise": "Economy, Business & Finance",
  "topic_pension": "Economy, Business & Finance",
  "topic_residential_real_estate": "Economy, Business & Finance",
  "topic_shipping_and_postal_service": "Economy, Business & Finance",
  "topic_handicrafts": "Economy, Business & Finance",
  "topic_start-up_and_entrepreneurial_business": "Economy, Business & Finance",
  "topic_mutual_funds": "Economy, Business & Finance",
  "topic_real_estate": "Economy, Business & Finance",
  "topic_rental_service": "Economy, Business & Finance",
  "topic_stocks_and_securities": "Economy, Business & Finance",
  "topic_bankruptcy": "Economy, Business & Finance",
  "topic_personal_service": "Economy, Business & Finance",
  "topic_industrial_production": "Economy, Business & Finance",
  "topic_business_strategy_and_marketing": "Economy, Business & Finance",
  "topic_patent,_copyright_and_trademark": "Economy, Business & Finance",
  "topic_personal_finance": "Economy, Business & Finance",
  "topic_financial_and_business_service": "Economy, Business & Finance",
  "topic_investments": "Economy, Business & Finance",
  "topic_economic_trends_and_indicators": "Economy, Business & Finance",
  "topic_pet_product_and_service": "Economy, Business & Finance",
  "topic_loan_market": "Economy, Business & Finance",
  "topic_restaurant_and_catering": "Economy, Business & Finance",
  "topic_casinos_and_gambling": "Economy, Business & Finance",
  "topic_profit_sharing": "Economy, Business & Finance",
  "topic_business_finance": "Economy, Business & Finance",
  "topic_asset_management": "Economy, Business & Finance",
  "topic_wholesale": "Economy, Business & Finance",
  "topic_viniculture": "Economy, Business & Finance",
  "topic_oil_and_gas_-_upstream_activities": "Economy, Business & Finance",
  "topic_construction_and_property": "Economy, Business & Finance",
  "topic_farms": "Economy, Business & Finance",
  "topic_forestry_and_timber": "Economy, Business & Finance",
  "topic_livestock_farming": "Economy, Business & Finance",
  "topic_insurance": "Economy, Business & Finance",
  "topic_government_debt": "Economy, Business & Finance",
  "topic_infrastructure_projects": "Economy, Business & Finance",
  "topic_cryptocurrency": "Economy, Business & Finance",
  "topic_podcast": "Economy, Business & Finance",
  "topic_radio_industry": "Economy, Business & Finance",
  "topic_television_industry": "Economy, Business & Finance",

  // Politics & Government
  "topic_politics_and_government": "Politics & Government",
  "topic_national_security": "Politics & Government",
  "topic_espionage_and_intelligence": "Politics & Government",
  "topic_international_relations": "Politics & Government",
  "topic_diplomacy": "Politics & Government",
  "topic_political_debates": "Politics & Government",
  "topic_election": "Politics & Government",
  "topic_housing_and_urban_planning_policy": "Politics & Government",
  "topic_judiciary": "Politics & Government",
  "topic_court": "Politics & Government",
  "topic_taxation_policy": "Politics & Government",
  "topic_prosecution_and_prosecutors": "Politics & Government",
  "topic_law_enforcement": "Politics & Government",
  "topic_police": "Politics & Government",
  "topic_political_parties_and_movements": "Politics & Government",
  "topic_political_system": "Politics & Government",
  "topic_political_movement_and_association": "Politics & Government",
  "topic_nuclear_policy": "Politics & Government",
  "topic_censorship_and_freedom_of_speech": "Politics & Government",
  "topic_data_protection_policy": "Politics & Government",
  "topic_legislative_body": "Politics & Government",
  "topic_political_party": "Politics & Government",
  "topic_supreme_and_high_court": "Politics & Government",
  "topic_local_government": "Politics & Government",
  "topic_public_officials": "Politics & Government",
  "topic_government_employee": "Politics & Government",
  "topic_government_budget": "Politics & Government",
  "topic_border_dispute": "Politics & Government",
  "topic_treaty": "Politics & Government",
  "topic_international_organization": "Politics & Government",
  "topic_immigration_policy": "Politics & Government",
  "topic_personal_weapon_control_policy": "Politics & Government",
  "topic_food_and_drink_regulations": "Politics & Government",
  "topic_regulations": "Politics & Government",
  "topic_antitrust_regulations": "Politics & Government",
  "topic_trade_policy": "Politics & Government",
  "topic_judge": "Politics & Government",
  "topic_surveillance": "Politics & Government",
  "topic_legal_service": "Politics & Government",
  "topic_court_administration": "Politics & Government",
  "topic_political_committee": "Politics & Government",
  "topic_campaign_finance": "Politics & Government",
  "topic_state_elections": "Politics & Government",
  "topic_primary_elections": "Politics & Government",
  "topic_local_elections": "Politics & Government",
  "topic_national_elections": "Politics & Government",
  "topic_intergovernmental_elections": "Politics & Government",
  "topic_voting": "Politics & Government",
  "topic_political_candidates": "Politics & Government",
  "topic_political_prisoners_and_dissenters": "Politics & Government",
  "topic_referendum": "Politics & Government",
  "topic_summit_meeting": "Politics & Government",
  "topic_arbitration_and_mediation": "Politics & Government",
  "topic_privacy": "Politics & Government",
  "topic_public_housing": "Politics & Government",
  "topic_government_aid": "Politics & Government",
  "topic_political_party_convention": "Politics & Government",
  "topic_pre-trial": "Politics & Government",
  "topic_veterans'_affairs": "Politics & Government",
  "topic_corruption": "Politics & Government",
  "topic_communism": "Politics & Government",
  "topic_dictatorship": "Politics & Government",
  "topic_nuclear_policy": "Politics & Government",
  "topic_foreign_aid": "Politics & Government",

  // Crime, Law & Justice
  "topic_crime,_law_and_justice": "Crime, Law & Justice",
  "topic_crime": "Crime, Law & Justice",
  "topic_justice": "Crime, Law & Justice",
  "topic_drug_related_crimes": "Crime, Law & Justice",
  "topic_drug_trafficking": "Crime, Law & Justice",
  "topic_organized_crime": "Crime, Law & Justice",
  "topic_gang_activity": "Crime, Law & Justice",
  "topic_assault": "Crime, Law & Justice",
  "topic_sex_crime": "Crime, Law & Justice",
  "topic_robbery_and_theft": "Crime, Law & Justice",
  "topic_homicide": "Crime, Law & Justice",
  "topic_arson": "Crime, Law & Justice",
  "topic_cyber_crime": "Crime, Law & Justice",
  "topic_kidnapping": "Crime, Law & Justice",
  "topic_missing_person": "Crime, Law & Justice",
  "topic_shootings": "Crime, Law & Justice",
  "topic_prostitution": "Crime, Law & Justice",
  "topic_fraud": "Crime, Law & Justice",
  "topic_embezzlement": "Crime, Law & Justice",
  "topic_anti-trust_crime": "Crime, Law & Justice",
  "topic_criminal_law": "Crime, Law & Justice",
  "topic_prison": "Crime, Law & Justice",
  "topic_arrest": "Crime, Law & Justice",
  "topic_witness": "Crime, Law & Justice",
  "topic_terrorism": "Crime, Law & Justice",
  "topic_act_of_terror": "Crime, Law & Justice",
  "topic_terrorist_bombings": "Crime, Law & Justice",
  "topic_reckless_driving": "Crime, Law & Justice",
  "topic_war_crime_action": "Crime, Law & Justice",
  "topic_capital_punishment": "Crime, Law & Justice",
  "topic_human_smuggling_and_trafficking": "Crime, Law & Justice",

  // Society
  "topic_society": "Society",
  "topic_family": "Society",
  "topic_mankind": "Society",
  "topic_psychology": "Society",
  "topic_Dating_and_Relationships": "Society",
  "topic_sexual_behavior": "Society",
  "topic_values": "Society",
  "topic_disabilities": "Society",
  "topic_gender": "Society",
  "topic_adoption": "Society",
  "topic_discrimination": "Society",
  "topic_racism": "Society",
  "topic_children": "Society",
  "topic_parents_group": "Society",
  "topic_death_and_dying": "Society",
  "topic_bullying": "Society",
  "topic_demographics": "Society",
  "topic_men": "Society",
  "topic_marriage": "Society",
  "topic_divorce": "Society",
  "topic_family_planning": "Society",
  "topic_contraception": "Society",
  "topic_refugees_and_internally_displaced_people": "Society",
  "topic_indigenous_people": "Society",
  "topic_illegal_immigration": "Society",
  "topic_immigration": "Society",
  "topic_population_and_census": "Society",
  "topic_senior_citizens": "Society",
  "topic_welfare": "Society",
  "topic_charity": "Society",
  "topic_pornography": "Society",
  "topic_infants": "Society",
  "topic_parenting": "Society",
  "topic_history": "Society",
  "topic_philosophy": "Society",
  "topic_social_sciences": "Society",
  "topic_religious_discrimination": "Society",
  "topic_funeral_home_and_crematorium": "Society",
  "topic_civil_rights": "Society",
  "topic_social_networking": "Society",
  "topic_slavery": "Society",
  "topic_national_or_ethnic_minority": "Society",

  // Health
  "topic_health": "Health",
  "topic_addiction": "Health",
  "topic_prescription_drugs": "Health",
  "topic_non-prescription_drug": "Health",
  "topic_disease_and_condition": "Health",
  "topic_mental_health": "Health",
  "topic_anxiety_and_stress": "Health",
  "topic_health_treatment_and_procedure": "Health",
  "topic_surgery": "Health",
  "topic_vaccine": "Health",
  "topic_therapy": "Health",
  "topic_heart_disease": "Health",
  "topic_medical_equipment": "Health",
  "topic_healthcare_industry": "Health",
  "topic_medical_profession": "Health",
  "topic_dentistry": "Health",
  "topic_medical_specialization": "Health",
  "topic_medical_service": "Health",
  "topic_medical_condition": "Health",
  "topic_diet": "Health",
  "topic_dietary_supplement": "Health",
  "topic_cancer": "Health",
  "topic_obesity": "Health",
  "topic_radiology": "Health",
  "topic_tobacco_and_nicotine": "Health",
  "topic_viral_disease": "Health",
  "topic_communicable_disease": "Health",
  "topic_HIV_and_AIDS": "Health",
  "topic_emergency_care": "Health",
  "topic_pregnancy_and_childbirth": "Health",
  "topic_reproductive_medicine": "Health",
  "topic_eye_care": "Health",
  "topic_public_health": "Health",
  "topic_pharmaceutical": "Health",
  "topic_health_insurance": "Health",
  "topic_depression": "Health",
  "topic_injury": "Health",
  "topic_physical_fitness": "Health",
  "topic_developmental_disorder": "Health",
  "topic_preventative_medicine": "Health",
  "topic_veterinary_medicine": "Health",
  "topic_non-human_diseases": "Health",
  "topic_animal_disease": "Health",
  "topic_elderly_care": "Health",
  "topic_euthanasia": "Health",
  "topic_suicide": "Health",
  "topic_healthcare_policy": "Health",
  "topic_health_organization": "Health",
  "topic_medical_staff": "Health",
  "topic_medical_test": "Health",
  "topic_poisoning": "Health",
  "topic_biomedical_science": "Health",
  "topic_abusive_behavior": "Health",
  "topic_orthopedics": "Health",

  // Conflict, War & Peace
  "topic_conflict,_war_and_peace": "Conflict, War & Peace",
  "topic_war": "Conflict, War & Peace",
  "topic_civil_unrest": "Conflict, War & Peace",
  "topic_armed_conflict": "Conflict, War & Peace",
  "topic_military_equipment": "Conflict, War & Peace",
  "topic_defense_equipment": "Conflict, War & Peace",
  "topic_prisoners_of_war": "Conflict, War & Peace",
  "topic_armed_forces": "Conflict, War & Peace",
  "topic_military_service": "Conflict, War & Peace",
  "topic_genocide": "Conflict, War & Peace",
  "topic_massacre": "Conflict, War & Peace",
  "topic_coup_d'etat": "Conflict, War & Peace",
  "topic_civil_war": "Conflict, War & Peace",
  "topic_riot": "Conflict, War & Peace",

  // Science & Technology
  "topic_science_and_technology": "Science & Technology",
  "topic_artificial_intelligence": "Science & Technology",
  "topic_information_technology_and_computer_science": "Science & Technology",
  "topic_computing_and_information_technology": "Science & Technology",
  "topic_software_and_applications": "Science & Technology",
  "topic_streaming_service": "Science & Technology",
  "topic_computer_and_telecommunications_hardware": "Science & Technology",
  "topic_telecommunication_equipment": "Science & Technology",
  "topic_telecommunication_service": "Science & Technology",
  "topic_satellite_and_cable_service": "Science & Technology",
  "topic_wireless_technology": "Science & Technology",
  "topic_space_exploration": "Science & Technology",
  "topic_aerospace": "Science & Technology",
  "topic_shipbuilding": "Science & Technology",
  "topic_machine_manufacturing": "Science & Technology",
  "topic_electrical_appliance": "Science & Technology",
  "topic_industrial_component": "Science & Technology",
  "topic_metal": "Science & Technology",
  "topic_mining": "Science & Technology",
  "topic_precious_material": "Science & Technology",
  "topic_plastic": "Science & Technology",
  "topic_building_material": "Science & Technology",
  "topic_geography": "Science & Technology",
  "topic_natural_science": "Science & Technology",
  "topic_astronomy": "Science & Technology",
  "topic_cosmology": "Science & Technology",
  "topic_physiology": "Science & Technology",
  "topic_physics": "Science & Technology",
  "topic_genetics": "Science & Technology",
  "topic_paleontology": "Science & Technology",
  "topic_scientific_research": "Science & Technology",
  "topic_scientific_institution": "Science & Technology",
  "topic_scientific_publication": "Science & Technology",
  "topic_information_science": "Science & Technology",
  "topic_marine_science": "Science & Technology",
  "topic_chemicals": "Science & Technology",
  "topic_nuclear_power": "Science & Technology",
  "topic_energy_resources": "Science & Technology",
  "topic_energy_and_resource": "Science & Technology",
  "topic_archeology": "Science & Technology",

  // Environment
  "topic_environment": "Environment",
  "topic_nature": "Environment",
  "topic_animal": "Environment",
  "topic_conservation": "Environment",
  "topic_environmental_policy": "Environment",
  "topic_environmental_pollution": "Environment",
  "topic_hazardous_materials": "Environment",
  "topic_rivers": "Environment",
  "topic_water": "Environment",
  "topic_flowers_and_plants": "Environment",
  "topic_forests": "Environment",
  "topic_parks": "Environment",
  "topic_mountains": "Environment",
  "topic_wetlands": "Environment",
  "topic_pests": "Environment",
  "topic_water_supply": "Environment",
  "topic_waste_management": "Environment",
  "topic_waste_materials": "Environment",
  "topic_water_pollution": "Environment",
  "topic_sustainability": "Environment",
  "topic_endangered_species": "Environment",
  "topic_climate_change": "Environment",
  "topic_global_warming": "Environment",
  "topic_plant_disease": "Environment",

  // Disaster & Emergency
  "topic_disaster,_accident_and_emergency_incident": "Disaster & Emergency",
  "topic_accident_and_emergency_incident": "Disaster & Emergency",
  "topic_disaster": "Disaster & Emergency",
  "topic_natural_disaster": "Disaster & Emergency",
  "topic_explosion_accident_and_incident": "Disaster & Emergency",
  "topic_industrial_accident_and_incident": "Disaster & Emergency",
  "topic_fire": "Disaster & Emergency",
  "topic_wildfire": "Disaster & Emergency",
  "topic_famine": "Disaster & Emergency",
  "topic_pandemic": "Disaster & Emergency",
  "topic_nuclear_accident_and_incident": "Disaster & Emergency",
  "topic_emergency_planning": "Disaster & Emergency",
  "topic_emergency_response": "Disaster & Emergency",
  "topic_volcanic_eruption": "Disaster & Emergency",
  "topic_hurricane": "Disaster & Emergency",
  "topic_nuclear_radiation_victims": "Disaster & Emergency",

  // Education
  "topic_education": "Education",
  "topic_school": "Education",
  "topic_university": "Education",
  "topic_college_and_university": "Education",
  "topic_curriculum": "Education",
  "topic_entrance_examination": "Education",
  "topic_primary_education": "Education",
  "topic_teachers": "Education",
  "topic_students": "Education",
  "topic_independent_and_charter_school": "Education",
  "topic_education_policy": "Education",

  // Labor
  "topic_labor": "Labor",
  "topic_occupations": "Labor",
  "topic_employment": "Labor",
  "topic_employment_statistics": "Labor",
  "topic_employer": "Labor",
  "topic_labor_dispute": "Labor",
  "topic_labor_strike": "Labor",
  "topic_unions": "Labor",
  "topic_human_resources": "Labor",
  "topic_job_layoffs": "Labor",
  "topic_apprenticeship": "Labor",
  "topic_social_security": "Labor",
  "topic_contract_issue-work_rules": "Labor",

  // Weather
  "topic_weather": "Weather",
  "topic_weather_statistic": "Weather",
  "topic_weather_forecast": "Weather",
  "topic_weather_warning": "Weather",
  "topic_weather_phenomena": "Weather",

  // Religion
  "topic_religion": "Religion",
  "topic_belief_systems": "Religion",
  "topic_Christianity": "Religion",
  "topic_Judaism": "Religion",
  "topic_Buddhism": "Religion",
  "topic_Mormonism": "Religion",
  "topic_Christian_Orthodoxy": "Religion",
  "topic_Methodist": "Religion",
  "topic_Ramadan": "Religion",
  "topic_Hanukkah": "Religion",
  "topic_Christmas": "Religion",
  "topic_cult": "Religion",
  "topic_church": "Religion",
  "topic_mosque": "Religion",
  "topic_temple": "Religion",
  "topic_religious_text": "Religion",

  // Countries (self-defined, exact list)
  "topic_china": "Countries",
  "topic_russia": "Countries",
  "topic_canada": "Countries",
  "topic_united_states": "Countries",
  "topic_mexico": "Countries",
  "topic_el_salvador": "Countries",
  "topic_israel": "Countries",
  "topic_iran": "Countries",
  "topic_united_kingdom": "Countries",
  "topic_taiwan": "Countries",
  "topic_saudi_arabia": "Countries",
  "topic_india": "Countries",
  "topic_pakistan": "Countries",

  // People (self-defined, exact list)
  "topic_donald_trump": "People",
  "topic_kamala_harris": "People",
  "topic_tim_walz": "People",
  "topic_jd_vance": "People",
  "topic_joe_biden": "People",
  "topic_bernie_sanders": "People",
  "topic_mike_johnson": "People",
  "topic_nancy_pelosi": "People",
  "topic_alexandria_ocasio-cortez": "People",
  "topic_mitch_mcconnell": "People",
  "topic_pete_buttigieg": "People",
  "topic_xi_jinping": "People",
  "topic_vladimir_putin": "People",
  "topic_volodymyr_zelensky": "People",
  "topic_benjamin_netanyahu": "People",
  "topic_claudia_sheinbaum": "People",
  "topic_ali_khamenei": "People",
  "topic_diddy": "People",
  "topic_luigi_mangione": "People",
  "topic_pope": "People",
  "topic_kanye_west": "People",
  "topic_jeff_bezos": "People",
  "topic_mark_zuckerberg": "People",
  "topic_tim_cook": "People",
  "topic_elon_musk": "People",
  "topic_sam_altman": "People",
  "topic_karoline_leavitt": "People",
  "topic_jeffrey_epstein": "People",
  "topic_mark_carney": "People",
  "topic_justin_trudeau": "People",
  "topic_robert_f._kennedy_jr": "People",
  "topic_pete_hegseth": "People",
  "topic_bob_menendez": "People",
  "topic_ron_desantis": "People",
  "topic_kevin_mccarthy": "People",
  "topic_chuck_schumer": "People",
  "topic_taylor_swift": "People",
  "topic_caitlin_clark": "People",

  // News Stories (self-defined, exact list)
  "topic_ice": "News Stories",
  "topic_democratic_party": "News Stories",
  "topic_republican_party": "News Stories",
  "topic_usaid": "News Stories",
  "topic_texas_floods": "News Stories",
  "topic_LGBTQ": "News Stories",
  "topic_israel_gaza": "News Stories",
  "topic_india_pakistan": "News Stories",
  "topic_russia_ukraine": "News Stories",
  "topic_fema": "News Stories",
  "topic_tiktok": "News Stories",
  "topic_crypto": "News Stories",
  "topic_tariffs": "News Stories",
  "topic_covid-19": "News Stories",
  "topic_taylor_swift_travis_kelce": "News Stories",
  "topic_opioids": "News Stories",

  // Catch-all
  "all_topics": "Other",
};